"""add_agent_configuration_models

Revision ID: 100c9e58f75d
Revises: b4c91912b2bd
Create Date: 2025-08-07 21:00:09.793526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100c9e58f75d'
down_revision: Union[str, None] = 'b4c91912b2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configurations',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('concurrent_limit', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.String(length=100), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=True),
    sa.Column('successful_executions', sa.Integer(), nullable=True),
    sa.Column('total_threats_found', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('average_execution_time', sa.Float(), nullable=True),
    sa.Column('average_confidence_score', sa.Float(), nullable=True),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configurations_agent_name'), 'agent_configurations', ['agent_name'], unique=True)
    op.create_index(op.f('ix_agent_configurations_id'), 'agent_configurations', ['id'], unique=False)
    op.create_table('agent_registry',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_class', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('requires_document', sa.Boolean(), nullable=True),
    sa.Column('requires_components', sa.Boolean(), nullable=True),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('enabled_by_default', sa.Boolean(), nullable=True),
    sa.Column('legacy_equivalent', sa.String(length=100), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('load_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_registry_agent_name'), 'agent_registry', ['agent_name'], unique=True)
    op.create_index(op.f('ix_agent_registry_id'), 'agent_registry', ['id'], unique=False)
    op.create_table('agent_execution_logs',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('execution_id', sa.String(length=100), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('had_document', sa.Boolean(), nullable=True),
    sa.Column('had_components', sa.Boolean(), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('threats_found', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=True),
    sa.Column('pipeline_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('execution_mode', sa.String(length=50), nullable=True),
    sa.Column('agent_config_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_logs_agent_name'), 'agent_execution_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_execution_id'), 'agent_execution_logs', ['execution_id'], unique=True)
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)
    op.create_table('agent_prompt_versions',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('average_threats', sa.Float(), nullable=True),
    sa.Column('agent_config_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_prompt_versions_agent_name'), 'agent_prompt_versions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_prompt_versions_id'), 'agent_prompt_versions', ['id'], unique=False)
    # Skip foreign key creation on pipeline_step_results - SQLite limitation
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_prompt_versions_id'), table_name='agent_prompt_versions')
    op.drop_index(op.f('ix_agent_prompt_versions_agent_name'), table_name='agent_prompt_versions')
    op.drop_table('agent_prompt_versions')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_execution_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_name'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    op.drop_index(op.f('ix_agent_registry_id'), table_name='agent_registry')
    op.drop_index(op.f('ix_agent_registry_agent_name'), table_name='agent_registry')
    op.drop_table('agent_registry')
    op.drop_index(op.f('ix_agent_configurations_id'), table_name='agent_configurations')
    op.drop_index(op.f('ix_agent_configurations_agent_name'), table_name='agent_configurations')
    op.drop_table('agent_configurations')
    # ### end Alembic commands ###
