"""Add threat feedback model

Revision ID: fe732f22db6c
Revises: 6d8b7b08bde9
Create Date: 2025-08-06 15:25:01.624298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe732f22db6c'
down_revision: Union[str, None] = '6d8b7b08bde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_feedback',
    sa.Column('threat_id', sa.String(length=100), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ACCEPTED', 'EDITED', 'DELETED', name='validationaction'), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('original_threat', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback_reason', sa.Text(), nullable=True),
    sa.Column('confidence_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_feedback_id'), 'threat_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_threat_feedback_threat_id'), 'threat_feedback', ['threat_id'], unique=False)
    
    # Only create foreign key for PostgreSQL (already handled in previous migration)
    # Skipping as this was already done in the previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping foreign key constraint for SQLite
    op.drop_index(op.f('ix_threat_feedback_threat_id'), table_name='threat_feedback')
    op.drop_index(op.f('ix_threat_feedback_id'), table_name='threat_feedback')
    op.drop_table('threat_feedback')
    # ### end Alembic commands ###
